# https://docs.readthedocs.io/en/stable/config-file/index.html
# https://docs.readthedocs.io/en/stable/guides/conda.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
conda:
  environment: environment.yml
python:
  install:
    - method: pip
      path: .
sphinx:
  configuration: docs/conf.py
  builder: "dirhtml"
  fail_on_warning: true
formats:
  - pdf
  - epub
  - htmlzip
