# run the following command to create a conda environment
# conda env create -f environment.yml
# conda activate soukdc
# update using
# conda env update --name soukdc --file environment.yml --prune
name: souk
channels:
  - conda-forge
dependencies:
  - archspec
  - python
  # extras
  - bump-my-version
  # tests
  - coverage
  - pytest
  # docs
  - furo
  - linkify-it-py
  - myst-parser
  - sphinx
  - sphinx-autobuild
  - sphinxcontrib-apidoc
  - pip:
    - sphinx-last-updated-by-git
