name: Linkcheck
on:
  workflow_run:
    workflows:
      - GitHub Pages
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install linkcheck
      run: curl -L https://github.com/ickc/bootstrapping-os-environments/raw/master/install/linkcheck.sh | bash
    - name: run linkcheck
      run: make linkcheck
