name: Linkcheck
on:
  workflow_run:
    workflows:
      - GitHub Pages
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install linkcheck
      run: |
        wget https://github.com/ickc/bootstrapping-os-environments/raw/master/install/linkcheck.sh
        bash linkcheck.sh
    - name: run linkcheck
      run: make linkcheck
