name: Linkcheck
on:
  workflow_run:
    workflows:
      - GitHub Pages
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: filiph/linkcheck@3.0.0
      with:
        arguments: '--external --no-check-anchors --skip-file docs/.skip.linkcheck https://docs-ci.souk.ac.uk'
