name: Unit tests
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # required by conda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        create-args: >-
          python=${{ matrix.python-version }}
        environment-file: environment.yml
    - name: Install
      run: |
        python -m pip install --no-dependencies -e .
    - name: Test
      run: |
        make coverage
